# Derived from https://github.com/route06/actions/blob/main/.github/workflows/dependency_review.yml
# Copyright (c) 2024 ROUTE06, Inc.
# Licensed under the MIT License.

name: Dependency Review

on:
  workflow_call:
    inputs:
      comment-summary-in-pr:
        description: Determines if the summary is posted as a comment in the PR itself. Setting this to `always` or `on-failure` requires you to give the workflow the write permissions for pull-requests
        default: on-failure
        required: false
        type: string

jobs:
  dependency_review:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4.8.2
        with:
          comment-summary-in-pr: ${{ inputs.comment-summary-in-pr }}
